# Generated by Django 3.1.4 on 2021-02-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yjuser',
            options={'verbose_name': 'YJ쇼핑의 사용자', 'verbose_name_plural': 'YJ쇼핑의 사용자'},
        ),
        migrations.AddField(
            model_name='yjuser',
            name='useremail',
            field=models.EmailField(default='test@gamil.com', max_length=128, verbose_name='사용자이메일'),
            preserve_default=False,
        ),
    ]
