# Generated by Django 3.1.4 on 2020-12-10 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201208_0810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '홈페이지 사용자', 'verbose_name_plural': '홈페이지 사용자'},
        ),
    ]
